#!/usr/bin/env bash
#
# run-ship-help-mcp.sh — start the ship-help-bot MCP server for the cluster_bot
# persona locally, so the ci-chat-bot ai-assistant's `researcher` tool has a
# research backend (CI/log investigation, verified knowledge, code browsing).
#
# It mints + Firestore-stores a service JWT, writes the env the ai-assistant
# needs to $SHIP_HELP_MCP_ENV_FILE, then runs the MCP server in the foreground
# (Ctrl-C to stop).
#
# All settings have local-dev defaults; override by exporting before running.
# Requires GCP application-default credentials:
#     gcloud auth application-default login
#
# Usage:
#     ai-assistant/hack/run-ship-help-mcp.sh
#     SHIP_HELP_DIR=/path/to/ship-help-bot MCP_PORT=8091 ai-assistant/hack/run-ship-help-mcp.sh
#
set -euo pipefail

# --- config (override by exporting before running) -------------------------
SHIP_HELP_DIR="${SHIP_HELP_DIR:-$HOME/source/ship-help-bot}"
export SLACK_WORKSPACE="${SLACK_WORKSPACE:-Sandbox-Testing}"
export GOOGLE_CLOUD_PROJECT="${GOOGLE_CLOUD_PROJECT:-openshift-crt}"
export GOOGLE_CLOUD_LOCATION="${GOOGLE_CLOUD_LOCATION:-global}"
export MCP_JWT_SECRET="${MCP_JWT_SECRET:-devsecret}"
export MCP_PERSONA="${MCP_PERSONA:-cluster_bot}"
export MCP_PORT="${MCP_PORT:-8091}"

TOKEN_FILE="${TOKEN_FILE:-/tmp/cluster-bot-mcp.jwt}"
SHIP_HELP_MCP_ENV_FILE="${SHIP_HELP_MCP_ENV_FILE:-/tmp/ship-help-mcp.env}"

# --- locate repo + venv ----------------------------------------------------
if [[ ! -d "$SHIP_HELP_DIR" ]]; then
  echo "error: ship-help-bot not found at $SHIP_HELP_DIR (set SHIP_HELP_DIR)" >&2
  exit 1
fi
cd "$SHIP_HELP_DIR"
PY="${PY:-$SHIP_HELP_DIR/.venv/bin/python}"
if [[ ! -x "$PY" ]]; then
  echo "error: python venv not found at $PY (set PY=/path/to/python)" >&2
  exit 1
fi

# --- mint + store the service token ----------------------------------------
echo "Minting cluster_bot MCP token (workspace=$SLACK_WORKSPACE project=$GOOGLE_CLOUD_PROJECT)…" >&2
"$PY" hack/mint-cluster-bot-token.py --save-token "$TOKEN_FILE"

# --- write the env the ai-assistant sources (0600) -------------------------
umask 077
cat > "$SHIP_HELP_MCP_ENV_FILE" <<EOF
# Generated by ai-assistant/hack/run-ship-help-mcp.sh — source before starting
# the ci-chat-bot ai-assistant so its \`researcher\` tool can reach this server.
# The token is referenced by FILE (read fresh on each researcher call), so
# re-minting — which revokes the previous token — is picked up WITHOUT
# restarting the ai-assistant.
export SHIP_HELP_MCP_URL="http://localhost:${MCP_PORT}/mcp"
export SHIP_HELP_MCP_TOKEN_FILE="${TOKEN_FILE}"
EOF

echo "Wrote ai-assistant env → $SHIP_HELP_MCP_ENV_FILE" >&2
echo >&2
echo "Now start the ai-assistant in a separate terminal:" >&2
echo "    ~/source/ci-chat-bot/ai-assistant/hack/run-with-research.sh" >&2
echo >&2

# --- run the MCP server (foreground) ---------------------------------------
echo "Starting MCP server: persona=$MCP_PERSONA port=$MCP_PORT path=/mcp (Ctrl-C to stop)…" >&2
exec "$PY" main.py mcp
